export const LOGIN_ACESS = 'LOGIN_ACESS';
export const REQUEST_FETCH = 'REQUEST_FETCH';
export const REQUEST_FETCH_SUCESS = 'REQUEST_FETCH_SUCESS';
export const REQUEST_FETCH_FAIL = 'REQUEST_FETCH_FAIL';
